
# Menu principal
MAIN_ADD_PLAYER = "1"
MAIN_LIST_PLAYERS = "2"
MAIN_TOURNAMENTS = "3"
MAIN_REPORTS = "4"
MAIN_QUIT = "5"

# Sous-menu tournois
TOURNAMENT_CREATE = "1"
TOURNAMENT_LOAD = "2"
TOURNAMENT_ADD_PLAYERS = "3"
TOURNAMENT_START_ROUND = "4"
TOURNAMENT_RECORD_RESULTS = "5"
TOURNAMENT_STANDINGS = "6"
TOURNAMENT_BACK = "0"

# Sous-menu rapports
REPORT_ALL_PLAYERS = "1"
REPORT_ALL_TOURNAMENTS = "2"
REPORT_TOURNAMENT_INFO = "3"
REPORT_TOURNAMENT_PLAYERS = "4"
REPORT_TOURNAMENT_ROUNDS = "5"
REPORT_BACK = "0"